// 세이프크로싱 — 시연용 표본 데이터셋
// 실데이터 구조(TAAS 보행사고 + 공공데이터포털 노인 통행 발생원 위치)를 따른 데모 표본입니다.
// 좌표·시설명은 평택시 실제 지명을 참조했으나 사고건수·거리 등 수치는 시연용 가상값입니다.

const SOURCE_TYPE_WEIGHTS = {
  '노인복지관': 1.0,
  '경로당': 0.8,
  '전통시장': 0.9,
  '병원': 0.7,
  '약국': 0.4,
};

// 거리구간별 가중치 테이블 f(도보거리) — 권장 이격 임계 100m, 거리 하한 10m
const DISTANCE_WEIGHT_TABLE = [
  { min: 0,   max: 100, w: 0.0, label: '100m 이하 (권장 이격 내)' },
  { min: 100, max: 200, w: 0.4, label: '100~200m' },
  { min: 200, max: 300, w: 0.7, label: '200~300m' },
  { min: 300, max: 500, w: 0.9, label: '300~500m' },
  { min: 500, max: Infinity, w: 1.0, label: '500m 초과' },
];

const SEGMENTS = [
  {
    id: 'PT-01',
    name: '통복시장 앞 통복로 구간',
    district: '통복동',
    lat: 36.9947, lng: 127.0838,
    crosswalkDist: 310,
    sources: [
      { type: '전통시장', name: '통복시장' },
      { type: '경로당', name: '통복동 경로당' },
      { type: '병원', name: '통복연합의원' },
      { type: '약국', name: '시장앞약국' },
    ],
    accidents3yr: 7, elderlyShare: 71, peak: '10~12시',
    hasSignalNearby: false, taasMatch: true,
  },
  {
    id: 'PT-02',
    name: '평택북부복지타운 진입로 구간',
    district: '서정동',
    lat: 37.0612, lng: 127.0521,
    crosswalkDist: 420,
    sources: [
      { type: '노인복지관', name: '평택북부복지타운' },
      { type: '경로당', name: '서정동 제2경로당' },
      { type: '약국', name: '서정온누리약국' },
    ],
    accidents3yr: 5, elderlyShare: 78, peak: '9~11시',
    hasSignalNearby: false, taasMatch: true,
  },
  {
    id: 'PT-03',
    name: '송탄시장 북측 탄현로 구간',
    district: '지산동',
    lat: 37.0758, lng: 127.0612,
    crosswalkDist: 260,
    sources: [
      { type: '전통시장', name: '송탄시장' },
      { type: '경로당', name: '지산동 경로당' },
      { type: '병원', name: '송탄중앙병원' },
    ],
    accidents3yr: 6, elderlyShare: 64, peak: '14~16시',
    hasSignalNearby: true, taasMatch: true,
  },
  {
    id: 'PT-04',
    name: '안중시장 서측 안현로 구간',
    district: '안중읍',
    lat: 36.9886, lng: 126.9312,
    crosswalkDist: 530,
    sources: [
      { type: '전통시장', name: '안중시장' },
      { type: '경로당', name: '안중리 경로당' },
    ],
    accidents3yr: 4, elderlyShare: 69, peak: '10~12시',
    hasSignalNearby: false, taasMatch: true,
  },
  {
    id: 'PT-05',
    name: '평택성모병원 후문 평남로 구간',
    district: '비전동',
    lat: 36.9903, lng: 127.1078,
    crosswalkDist: 230,
    sources: [
      { type: '병원', name: '평택성모병원' },
      { type: '약국', name: '성모약국' },
      { type: '경로당', name: '비전1동 경로당' },
    ],
    accidents3yr: 5, elderlyShare: 58, peak: '9~11시',
    hasSignalNearby: true, taasMatch: true,
  },
  {
    id: 'PT-06',
    name: '서정리역 동측 서정역로 구간',
    district: '서정동',
    lat: 37.0589, lng: 127.0563,
    crosswalkDist: 180,
    sources: [
      { type: '전통시장', name: '서정리시장' },
      { type: '약국', name: '서정리역약국' },
      { type: '경로당', name: '서정동 제1경로당' },
    ],
    accidents3yr: 3, elderlyShare: 52, peak: '15~17시',
    hasSignalNearby: true, taasMatch: false,
  },
  {
    id: 'PT-07',
    name: '합정주공 앞 경기대로 이면 구간',
    district: '합정동',
    lat: 36.9858, lng: 127.0989,
    crosswalkDist: 340,
    sources: [
      { type: '경로당', name: '합정동 주공경로당' },
      { type: '병원', name: '합정연세의원' },
      { type: '약국', name: '주공약국' },
    ],
    accidents3yr: 4, elderlyShare: 66, peak: '10~12시',
    hasSignalNearby: false, taasMatch: true,
  },
  {
    id: 'PT-08',
    name: '팽성읍 객사리 부용로 구간',
    district: '팽성읍',
    lat: 36.9612, lng: 127.1128,
    crosswalkDist: 610,
    sources: [
      { type: '경로당', name: '객사리 경로당' },
      { type: '약국', name: '팽성약국' },
    ],
    accidents3yr: 3, elderlyShare: 74, peak: '8~10시',
    hasSignalNearby: false, taasMatch: true,
  },
  {
    id: 'PT-09',
    name: '굿모닝병원 앞 중앙로 구간',
    district: '세교동',
    lat: 37.0042, lng: 127.0701,
    crosswalkDist: 150,
    sources: [
      { type: '병원', name: '굿모닝병원' },
      { type: '약국', name: '굿모닝약국' },
    ],
    accidents3yr: 2, elderlyShare: 49, peak: '9~11시',
    hasSignalNearby: true, taasMatch: false,
  },
  {
    id: 'PT-10',
    name: '평택중앙시장 남측 명동길 구간',
    district: '평택동',
    lat: 36.9899, lng: 127.0867,
    crosswalkDist: 280,
    sources: [
      { type: '전통시장', name: '평택중앙시장' },
      { type: '경로당', name: '평택동 경로당' },
      { type: '약국', name: '중앙약국' },
    ],
    accidents3yr: 5, elderlyShare: 61, peak: '11~13시',
    hasSignalNearby: false, taasMatch: true,
  },
  {
    id: 'PT-11',
    name: '비전동 행정복지센터 앞 비전5로 구간',
    district: '비전동',
    lat: 36.9931, lng: 127.1124,
    crosswalkDist: 120,
    sources: [
      { type: '경로당', name: '비전2동 경로당' },
      { type: '약국', name: '비전약국' },
    ],
    accidents3yr: 1, elderlyShare: 46, peak: '14~16시',
    hasSignalNearby: true, taasMatch: false,
  },
  {
    id: 'PT-12',
    name: '지산초교 북측 지산로 구간',
    district: '지산동',
    lat: 37.0801, lng: 127.0648,
    crosswalkDist: 390,
    sources: [
      { type: '경로당', name: '지산동 제3경로당' },
      { type: '병원', name: '지산가정의원' },
    ],
    accidents3yr: 3, elderlyShare: 63, peak: '10~12시',
    hasSignalNearby: false, taasMatch: false,
  },
  {
    id: 'PT-13',
    name: '안중읍 보건지소 앞 서동대로 이면 구간',
    district: '안중읍',
    lat: 36.9851, lng: 126.9278,
    crosswalkDist: 460,
    sources: [
      { type: '병원', name: '안중보건지소' },
      { type: '경로당', name: '학현리 경로당' },
      { type: '약국', name: '안중제일약국' },
    ],
    accidents3yr: 4, elderlyShare: 72, peak: '9~11시',
    hasSignalNearby: false, taasMatch: true,
  },
  {
    id: 'PT-14',
    name: '동삭동 LH단지 앞 동삭로 구간',
    district: '동삭동',
    lat: 37.0151, lng: 127.0712,
    crosswalkDist: 200,
    sources: [
      { type: '경로당', name: '동삭동 LH경로당' },
      { type: '약국', name: '동삭메디칼약국' },
    ],
    accidents3yr: 2, elderlyShare: 44, peak: '16~18시',
    hasSignalNearby: true, taasMatch: false,
  },
  {
    id: 'PT-15',
    name: '평택역 서부광장 평택로 이면 구간',
    district: '평택동',
    lat: 36.9914, lng: 127.0832,
    crosswalkDist: 90,
    sources: [
      { type: '약국', name: '역전약국' },
      { type: '병원', name: '평택역내과' },
    ],
    accidents3yr: 1, elderlyShare: 38, peak: '17~19시',
    hasSignalNearby: true, taasMatch: false,
  },
  {
    id: 'PT-16',
    name: '독곡동 송탄도서관 앞 독곡로 구간',
    district: '독곡동',
    lat: 37.0852, lng: 127.0571,
    crosswalkDist: 350,
    sources: [
      { type: '경로당', name: '독곡동 경로당' },
      { type: '노인복지관', name: '송탄노인복지관' },
    ],
    accidents3yr: 4, elderlyShare: 75, peak: '9~11시',
    hasSignalNearby: false, taasMatch: true,
  },
];
